name = "novel-site-d1"

# Cloudflare Pages配置
pages_build_output_dir = ".next"

# 兼容性配置
compatibility_date = "2026-04-23"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
NODE_ENV = "production"
NODE_VERSION = "20"

# 部署配置
[deployment]
environment = "production"

[[d1_databases]]
binding = "DB"
database_name = "novel-site-db"
database_id = "be4e1044-b2b0-47ef-b2aa-7aca4687a717"